inviteme:
  image:
    # reference local version of image, somehow tilt figures this out? idk, leaving as-is
    repository: invite-me
  otelCollector:
    logs:
      endpoint: http://otel-collector.invite-me-dev.svc.cluster.local:4317
